services:
  mysql:
    image: mysql:8.0
    container_name: petjoy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: petjoy
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: petjoy-app
    depends_on:
      - mysql
    stdin_open: true
    tty: true

